### ISSUE TITLE
Template: All jobs have failed

### ISSUE THREAD

**Issue by halloleo** [jecklgamis/springboot-scala-example#12]
Firstly, thanks for the template. I'm looking forward to experimenting with Spring Boot in Scala.

When forking this repo as a template and making no changes to it at all, I get soon an email with subject "[username/spring-boot-scala-example] Rain failed: Template - main".

As far as I understand it, the template installs some actions, but for some reason they fail, even when nothing has changed.

How to fix this?

**Comment by jecklgamis** [comment]
Hey @halloleo I just setup notification on this, my apologies. What specific error did you get from Github?

**Comment by halloleo** [comment]
@jecklgamis Thanks for looking at this!

But sorry, I moved on from using Spring in Scala and cannot recall the error I got.

Happy to close this as outdated.
